version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: mreichelt/android:28
    environment:
      # from https://discuss.circleci.com/t/circle-ci-v2-and-android-memory-issues/11207
      JVM_OPTS: "-Xmx1024m -XX:+PrintFlagsFinal -XX:+PrintGCDetails"
      _JAVA_OPTIONS: "-Xmx1024m"
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "build.gradle" }}-{{ checksum  "manifest-config-annotations/build.gradle" }}-{{ checksum  "manifest-config-processor/build.gradle" }}-{{ checksum  "manifest-config-sample/build.gradle" }}
      - run: ./gradlew androidDependencies # does this work?
      - run: ./gradlew check -s --info
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-{{ checksum "build.gradle" }}-{{ checksum  "manifest-config-annotations/build.gradle" }}-{{ checksum  "manifest-config-processor/build.gradle" }}-{{ checksum  "manifest-config-sample/build.gradle" }}
      - store_artifacts:
          path: ~/code/manifest-config-annotations/build/libs
          destination: annotations/
      - store_artifacts:
          path: ~/code/manifest-config-processor/build/libs
          destination: processor/
      - store_artifacts:
          path: ~/code/manifest-config-sample/build/outputs
          destination: sample/
      - store_test_results:
          path: ~/code/manifest-config-processor/build/reports
      - store_test_results:
          path: ~/code/manifest-config-sample/build/reports