version: 2.1

orbs:
  android-sdk: rakutentech/android-sdk@0.2.1
  app-center: rakutentech/app-center@0.1.2

workflows:
  version: 2.1
  build-and-release:
    jobs:
      - android-sdk/build:
          gradle-cache-key: >-
            gradle-
            {{ checksum "build.gradle" }}
            {{ checksum  "manifest-config-annotations/build.gradle" }}
            {{ checksum  "manifest-config-processor/build.gradle" }}
            {{ checksum  "manifest-config-sample/build.gradle" }}
          sdk-path: manifest-config-processor
          sample-app-path: manifest-config-sample
          post-steps:
            - persist_to_workspace:
                root: ~/code
                paths:
                  - manifest-config-annotations/build/
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - release-verification:
          type: approval
          requires:
            - android-sdk/build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - android-sdk/publish:
          requires:
            - release-verification
          after-prepare-steps:
            # Retrieve Base64 PGP Key and save to file
            - run: |
                if [[ "$RELEASE_PGP_KEY_BASE64" != "" ]]; then
                  base64 -d \<<< "$RELEASE_PGP_KEY_BASE64" > ./maven-central-key.gpg
                fi
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
